---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-redis-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask-redis-k8s
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ecerulm/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources: {}
      imagePullSecrets:
      - name: gitlab-credentials
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: flask-redis-k8s
spec:
  ports:
    - name: amundsen-frontend-amundsen-test-http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
      app: flask
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flask-redis-k8s
  name: flask
spec:
  rules:
  - host: myflask.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: flask
            port:
              number: 8000